version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  intranetportal:
    image: ${DOCKER_REGISTRY-}intranetportal
    depends_on:
      - "postgres" 
    build:
      context: .
      dockerfile: IntranetPortal/Dockerfile
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=IntranetDB;username=postgres;password=TasacIntranetDB@2022"
    networks:
      - dockerapi-dev

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "TasacIntranetDB@2022"
      POSTGRES_DB: "IntranetDB"
    networks:
      - dockerapi-dev
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL="ictsupport@tasac.go.tz"
      - PGADMIN_DEFAULT_PASSWORD="TasacIntranetDB@2018"
    ports:
      - "5050:80"
    networks:
      - dockerapi-dev 
    restart: always
